samples: "/hpcfs/users/a1627307/star_t2d/star_t2d/config/female_samples.tsv"
chr_prefix: "chr"
chrs: '1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y'
annotationbase: "gencode.v45.primary_assembly.annotation"
graphbase: "hprc-v1.1-mc-grch38"



autoindex:
  workflow_a: "mpmap"
  workflow_b: "rpvg"

chunk:
  out_format: "gfa"

snarls: 
  algorithm: "integrated"

mpmap:
  nt_type: "rna"

featureCounts:
  minQual: 1
  minOverlap: 35
  fracOverlap: 0.9
  strandedness: 0 # Changed from 1 to 2 to 0 as counts were way too low
  extra: "-p -B -M --fraction" 
  # gtf: "/hpcfs/user/a1627307/genome/gencode.v45.primary_assembly.annotation.gtf"